# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazonprime
  namespace: manikiran
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazonprime
  template:
    metadata:
      labels:
        app: amazonprime
    spec:
      containers:
        - name: amazonprime
          image: 231778609415.dkr.ecr.us-east-1.amazonaws.com/manikiran/amazonprime:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-creds
